if FALSE:
    outer let string = "lol"

try:
    print("succeeding try")
finally:
    print("succeeding finally")

print("---------")

try:
    try:
        print("failing try")
        print(string)
    finally:
        print("succeeding finally")
catch VariableError e:
    print("got error {e}")

print("---------")

try:
    try:
        print("succeeding try")
    finally:
        print("failing finally")
        print(string)
catch VariableError e:
    print("got error {e}")

print("---------")

try:
    try:
        print("failing try")
        print(string)
    finally:
        print("failing finally")
        print(string)
catch VariableError e:
    print("got error {e}")
